# Production context: all deploys from the Production branch 
# set in your site’s Branches settings in the UI will inherit 
# these settings. You can define environment variables 
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository. 
[context.production]
  environment = { NODE_VERSION = "14.17.3" }

[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  YARN_VERSION = "1.22.15"
  YARN_FLAGS = "--no-ignore-optional"